### ISSUE TITLE
Error: Cannot find module 'babel-polyfill'

### ISSUE THREAD

**Issue by weber-d** [tkshnwesper/couchdb-expression#2]
After installing the npm package as described in the documentation, I got the compilation error

> Error: Cannot find module 'babel-polyfill'

As a workaround, this can be fixed by installing the package manually in your project using `npm i -P babel-polyfill`. But this shouldnt be required, when the package is referenced as dependeny in `couchdb-expression` itself.

**Comment by greenais** [comment]
The same here using yarn.
That's strange since babel-polyfill is listed in module's package.json, but in dev section.

**Comment by smachave** [comment]
My apologies on this one as well, turns out that I didn't know npm packaging as well as I'd have liked to.

The latest update to the library should be able to resolve this.
